In [2]:
%%sql
CREATE TABLE dbo.customer (
    id       INT,
    name     VARCHAR(255),
    genre    VARCHAR(1),
    birthday DATE
);

INSERT INTO dbo.Customer (id, name, genre, birthday)
VALUES
    (1, 'Ana Paula Silva',        'F', '1992-04-18'),
    (2, 'Carlos Eduardo Santos',  'M', '1985-11-02'),
    (3, 'Mariana Oliveira',       'F', '1998-07-25'),
    (4, 'João Pedro Almeida',     'M', '2001-01-09'),
    (5, 'Fernanda Costa',         'F', '1990-09-14'),
    (6, 'Lucas Henrique Rocha',   'M', '1995-03-30'),
    (7, 'Beatriz Nogueira',       'F', '1988-12-05'),
    (8, 'Rafael Moreira Lima',    'M', '2003-06-21');

StatementMeta(, 6b54f9f8-c272-47c0-bc15-50815581e28f, 4, Finished, Available, Finished)

In [24]:
%%sql
INSERT INTO dbo.Customer (id, name, genre, birthday)
VALUES
    (9,  'Patrícia Azevedo',     'F', '1993-02-11');

StatementMeta(, 6b54f9f8-c272-47c0-bc15-50815581e28f, 27, Finished, Available, Finished)

In [27]:
%%sql
INSERT INTO dbo.Customer (id, name, genre, birthday)
VALUES
    (10, 'Bruno Matheus Pires',  'M', '1987-08-27');

StatementMeta(, 6b54f9f8-c272-47c0-bc15-50815581e28f, 30, Finished, Available, Finished)

In [35]:
result = client.post(url, json=payload)

# import pandas as pd
pd.json_normalize(result.json().get("value"))

StatementMeta(, 6b54f9f8-c272-47c0-bc15-50815581e28f, 38, Finished, Available, Finished)

,tableName,status,startDateTime,endDateTime,lastSuccessfulSyncDateTime
0,dbo.customer,NotRun,2025-12-29T01:41:16.4669129Z,2025-12-29T01:41:16.5450685Z,2025-12-29T01:33:02.7939058Z

In [ ]:
%%sql
INSERT INTO dbo.Customer (id, name, genre, birthday)
VALUES
    (11, 'Camila Rangel Souza',  'F', '2000-05-03');

In [25]:
%%sql
SELECT * FROM dbo.customer
ORDER BY id ASC

StatementMeta(, 6b54f9f8-c272-47c0-bc15-50815581e28f, 28, Finished, Available, Finished)

In [5]:
import sempy.fabric as fabric

#Instantiate the client
client = fabric.FabricRestClient()

StatementMeta(, 6b54f9f8-c272-47c0-bc15-50815581e28f, 8, Finished, Available, Finished)

In [13]:
workspace_id = "6d937f70-5386-464e-9e43-f8d5a1fa2551" 
sql_endpoint_id = "cd4a4ee9-acab-4d40-a185-1f8b4f3238ee"
semantic_model_id = ""

StatementMeta(, 6b54f9f8-c272-47c0-bc15-50815581e28f, 16, Finished, Available, Finished)

In [26]:
url = f"v1/workspaces/{workspace_id}/sqlEndpoints/{sql_endpoint_id}/refreshMetadata"

payload = {
    "timeout": {
        "timeUnit": "Minutes",
        "value": 15
    }
}

StatementMeta(, 6b54f9f8-c272-47c0-bc15-50815581e28f, 29, Finished, Available, Finished)

,tableName,status,startDateTime,endDateTime,lastSuccessfulSyncDateTime
0,dbo.customer,Success,2025-12-29T01:31:06.8872728Z,2025-12-29T01:31:07.3404035Z,2025-12-29T01:31:07.3404035Z

In [39]:
url = f"v1/workspaces/{workspace_id}/sqlEndpoints/{sql_endpoint_id}/connectionString"

response = client.get(url)

connection_string = response.json().get("connectionString") 
print(connection_string)

StatementMeta(, 6b54f9f8-c272-47c0-bc15-50815581e28f, 42, Finished, Available, Finished)

gvkmt76pz4cuhm2fs63qgxl5cy-ob7zg3mgknhenhsd7dk2d6rfke.datawarehouse.fabric.microsoft.com

In [40]:
url = f"v1/workspaces/{workspace_id}/sqlEndpoints"
response = client.get(url)

pd.json_normalize(response.json().get("value"))

StatementMeta(, 6b54f9f8-c272-47c0-bc15-50815581e28f, 43, Finished, Available, Finished)

,id,type,displayName,description,workspaceId
0,cd4a4ee9-acab-4d40-a185-1f8b4f3238ee,SQLEndpoint,Lakehouse01,,6d937f70-5386-464e-9e43-f8d5a1fa2551